In [3]:
sex = ['male','male','female','male','female','female']

import numpy as np
sex_conv = np.zeros(6)
cnt = 0
for x in sex:
  if(x == 'female'):
    sex_conv[cnt] = 1
  cnt = cnt+1
print(sex_conv)

[0. 0. 1. 0. 1. 1.]


In [5]:
from tensorflow.keras.utils import to_categorical

sex_cate = to_categorical(sex_conv)
print(sex_cate)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]


In [8]:
pclass_orig = np.array([3,1,2,1,2,3])

from tensorflow.keras.utils import to_categorical
pclass_cate = to_categorical(pclass_orig-1)

print(pclass_cate)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
